environment:
  matrix:
    - PYTHON: "C:/Python37-x64"
      ENABLE_CONTRIB: 0
      ENABLE_HEADLESS: 0

matrix:
    fast_finish: true

build_script:
- cmd: |
    "%PYTHON%/python.exe" -m pip install --upgrade pip
    "%PYTHON%/python.exe" -m pip install --upgrade setuptools
    "%PYTHON%/python.exe" setup.py bdist_wheel

before_test:
- ps: |

    cd ${Env:APPVEYOR_BUILD_FOLDER}\tests
    $env:PYTHONWARNINGS = "ignore:::pip._internal.cli.base_command"
    &"${Env:PYTHON}/python.exe" -m pip install --user (ls "../dist/opencv_*.whl")
    if ($LastExitCode -ne 0) {throw $LastExitCode}

test_script:
- cmd: |

    cd %APPVEYOR_BUILD_FOLDER%\tests
    "%PYTHON%/python.exe" -m unittest test

artifacts:
- path: dist\*.whl
  name: wheels

deploy_script:
- ps: |

      echo "Tag not set, deployment skipped."
